In [1]:
import pandas as pd
import numpy as np
import uncertainties as uc

pd.options.display.float_format ='{:,.1e}'.format
import matplotlib.pyplot as plt
%matplotlib inline  
from IPython.display import Image
from IPython.core.display import HTML 

from openpyxl import load_workbook

from scipy import integrate
import scipy.stats as stats
from uncertainties import ufloat
from uncertainties import unumpy
from itertools import groupby

from scipy.stats import gmean

%run Utility_Functions.ipynb

# Result summary
This notebook able to run all other notebooks and gather all the results in one place

## Running all notebooks

Creating a class that can load a notebook and execute it

In [2]:
import io, os, sys, types
from IPython import get_ipython
from nbformat import read
from IPython.core.interactiveshell import InteractiveShell

def find_notebook(fullname, path=None):
    """find a notebook, given its fully qualified name and an optional path

    This turns "foo.bar" into "foo/bar.ipynb"
    and tries turning "Foo_Bar" into "Foo Bar" if Foo_Bar
    does not exist.
    """
    name = fullname.rsplit('.', 1)[-1]
    if not path:
        path = ['']
    for d in path:
        nb_path = os.path.join(d, name + ".ipynb")
        if os.path.isfile(nb_path):
            return nb_path
        # let import Notebook_Name find "Notebook Name.ipynb"
        nb_path = nb_path.replace("_", " ")
        if os.path.isfile(nb_path):
            return nb_path



class NotebookLoader(object):
    """Module Loader for Jupyter Notebooks"""
    def __init__(self, path=None):
        self.shell = InteractiveShell.instance()
        self.path = path

    def load_module(self, fullname):
        """import a notebook as a module"""
        path = find_notebook(fullname, self.path)

        print ("importing Jupyter notebook from %s" % path)

        # load the notebook object
        with io.open(path, 'r', encoding='utf-8') as f:
            nb = read(f, 4)


        # create the module and add it to sys.modules
        # if name in sys.modules:
        #    return sys.modules[name]
        mod = types.ModuleType(fullname)
        mod.__file__ = path
        mod.__loader__ = self
        mod.__dict__['get_ipython'] = get_ipython
        sys.modules[fullname] = mod

        # extra work to ensure that magics that would affect the user_ns
        # actually affect the notebook module's ns
        save_user_ns = self.shell.user_ns
        self.shell.user_ns = mod.__dict__

        try:
            for cell in nb.cells:
                if cell.cell_type == 'code':
                    # transform the input to executable Python
                    code = self.shell.input_transformer_manager.transform_cell(cell.source)
                    exec(code, mod.__dict__);
        finally:
            self.shell.user_ns = save_user_ns
        return mod

In [7]:
%%capture  

#suppres the many outputs of the notebook for this run  
 
notebooks = ['Erythrocytes','Neutrophils','Lymphocytes','Monocytes','GIT Epithelial Cells', 'Skin cells',
             'Endothelial cells','Lung cells', 'Adipocytes','Myocytes','Cardiomyocytes','Brain Cells', 'Liver cells']
NBL = NotebookLoader()
for nb_name in notebooks:
    NBL.load_module(nb_name)

KeyError: '% T cells'

## Loading the concentated data
Importing from the excel into a CellTypesResDF object and using it to print all the results.
In addition, the object method enable to deal with the data. For example the extended Dataframe of all the results including the upper and lower bound is computed

In [8]:
cell_types_data = pd.read_excel('Summary.xlsx','Colors', index_col=0, usecols=range(4))
cell_types_data = cell_types_data.drop('Other')

cells = CellTypesResDF(cell_types_data.index,un_type='mixed')
cells.import_celltypes_from_xlsx('Summary.xlsx')
cells.print_params()
cells.get_extended_dataframe()

Erythrocytes:
Number of Erythrocytes is: (2.5±0.1)×10¹³ cells
Lifespan of Erythrocytes is: 119±3 days
Cellular turnover rate of Erythrocytes is: (2.1±0.1)×10¹¹ cells per day
Cell mass of Erythrocytes is: 94±3 pg
Cellular mass turnover rate of Erythrocytes is: 20.00±1.00 grams per day
Total cellular mass of Erythrocytes is: 2380±100 grams
______________________________
Neutrophils:
Number of Neutrophils is: (6.4±0.6)×10¹¹ cells
Lifespan of Neutrophils is: 6.6±0.5 days
Cellular turnover rate of Neutrophils is: (6.0±1.5)×10¹⁰ cells per day
Cell mass of Neutrophils is: 300±30 pg
Cellular mass turnover rate of Neutrophils is: 18±5 grams per day
Total cellular mass of Neutrophils is: 190±30 grams
______________________________
Monocytes:
Number of Monocytes is: 5e+09 cells (SD range: 4e+09 - 8e+09 cells)
Lifespan of Monocytes is: 4 days (SD range: 3 - 4 days)
Cellular turnover rate of Monocytes is: 2e+09 cells per day (SD range: 1e+09 - 2e+09 cells per day)
Cell mass of Monocytes is: 460 pg (SD range: 420 - 510 pg)
Cellular mass turnover rate of Monocytes is: 0.7 grams per day (SD range: 0.5 - 1.1 grams per day)
Total cellular mass of Monocytes is: 2.4 grams (SD range: 1.6 - 3.6 grams)
______________________________
Thymocytes:
Number of Thymocytes is: 2e+09 cells (SD range: 5e+08 - 1e+10 cells)
Cell mass of Thymocytes is: 190 pg (SD range: 170 - 210 pg)
Total cellular mass of Thymocytes is: 0.43 grams (SD range: 0.09 - 2.10 grams)
Lifespan in rodents of Thymocytes is: 3.8 days (SD range: 1.6 - 8.7 days)
Extrapolated cellular turnover rate of Thymocytes is: 6e+08 cells per day (SD range: 1e+08 - 4e+09 cells per day)
Extrapolated cellular mass turnover rate of Thymocytes is: 0.11 grams per day (SD range: 0.02 - 0.69 grams per day)
______________________________
Mature T cells:
Number of Mature T cells is: 7e+11 cells (SD range: 3e+11 - 2e+12 cells)
Lifespan of Mature T cells is: 320 days (SD range: 240 - 430 days)
Cellular turnover rate of Mature T cells is: 2e+09 cells per day (SD range: 1e+09 - 5e+09 cells per day)
Cell mass of Mature T cells is: 190 pg (SD range: 170 - 210 pg)
Cellular mass turnover rate of Mature T cells is: 0.4 grams per day (SD range: 0.2 - 0.9 grams per day)
Total cellular mass of Mature T cells is: 132 grams (SD range: 60 - 290 grams)
______________________________
B cells progenitors:
Number of B cells progenitors is: 6e+09 cells (SD range: 4e+09 - 8e+09 cells)
Cell mass of B cells progenitors is: 190 pg (SD range: 170 - 210 pg)
Total cellular mass of B cells progenitors is: 1.0 grams (SD range: 0.7 - 1.5 grams)
Lifespan in rodents of B cells progenitors is: 0.8 days (SD range: 0.4 - 1.7 days)
Extrapolated cellular turnover rate of B cells progenitors is: 7e+09 cells per day (SD range: 4e+09 - 1e+10 cells per day)
Extrapolated cellular mass turnover rate of B cells progenitors is: 1.2 grams per day (SD range: 0.7 - 2.2 grams per day)
______________________________
Transitional B cells:
Number of Transitional B cells is: 3e+09 cells (SD range: 1e+09 - 7e+09 cells)
Cell mass of Transitional B cells is: 190 pg (SD range: 170 - 210 pg)
Total cellular mass of Transitional B cells is: 0.5 grams (SD range: 0.2 - 1.3 grams)
Lifespan in rodents of Transitional B cells is: 10 days (SD range: 8 - 12 days)
Extrapolated cellular turnover rate of Transitional B cells is: 3e+08 cells per day (SD range: 1e+08 - 7e+08 cells per day)
Extrapolated cellular mass turnover rate of Transitional B cells is: 0.05 grams per day (SD range: 0.02 - 0.13 grams per day)
______________________________
Mature B cells:
Number of Mature B cells is: 3e+11 cells (SD range: 1e+11 - 7e+11 cells)
Lifespan of Mature B cells is: 63 days (SD range: 52 - 76 days)
Cellular turnover rate of Mature B cells is: 5e+09 cells per day (SD range: 2e+09 - 1e+10 cells per day)
Cell mass of Mature B cells is: 190 pg (SD range: 170 - 210 pg)
Cellular mass turnover rate of Mature B cells is: 0.9 grams per day (SD range: 0.4 - 2.2 grams per day)
Total cellular mass of Mature B cells is: 59 grams (SD range: 27 - 130 grams)
______________________________
Dermal fibroblasts:
Number of Dermal fibroblasts is: (3.8±1.6)×10¹⁰ cells
Cell mass of Dermal fibroblasts is: 2300±200 pg
Total cellular mass of Dermal fibroblasts is: 90±40 grams
Lifespan in rodents of Dermal fibroblasts is: 140±20 days
Extrapolated cellular turnover rate of Dermal fibroblasts is: (2.7±1.2)×10⁸ cells per day
Extrapolated cellular mass turnover rate of Dermal fibroblasts is: 0.6±0.3 grams per day
______________________________
Epidermal cells:
Number of Epidermal cells is: (1.2±0.3)×10¹¹ cells
Lifespan of Epidermal cells is: 31±4 days
Cellular turnover rate of Epidermal cells is: (3.7±0.9)×10⁹ cells per day
Cell mass of Epidermal cells is: 830±30 pg
Cellular mass turnover rate of Epidermal cells is: 3.1±0.8 grams per day
Total cellular mass of Epidermal cells is: 100±20 grams
______________________________
Alveolar epithelial cells:
Number of Alveolar epithelial cells is: 1e+11 cells (SD range: 9e+10 - 1e+11 cells)
Cell mass of Alveolar epithelial cells is: 2200 pg (SD range: 1900 - 2600 pg)
Total cellular mass of Alveolar epithelial cells is: 240 grams (SD range: 190 - 300 grams)
Lifespan in rodents of Alveolar epithelial cells is: 32 days (SD range: 29 - 36 days)
Extrapolated cellular turnover rate of Alveolar epithelial cells is: 4e+09 cells per day (SD range: 3e+09 - 4e+09 cells per day)
Extrapolated cellular mass turnover rate of Alveolar epithelial cells is: 8 grams per day (SD range: 6 - 10 grams per day)
______________________________
Bronchial epithelial cells:
Number of Bronchial epithelial cells is: 1e+10 cells (SD range: 9e+09 - 1e+10 cells)
Lifespan of Bronchial epithelial cells is: 139 days (SD range: 109 - 180 days)
Cellular turnover rate of Bronchial epithelial cells is: 8e+07 cells per day (SD range: 6e+07 - 1e+08 cells per day)
Cell mass of Bronchial epithelial cells is: 890 pg (SD range: 790 - 1010 pg)
Cellular mass turnover rate of Bronchial epithelial cells is: 0.07 grams per day (SD range: 0.05 - 0.09 grams per day)
Total cellular mass of Bronchial epithelial cells is: 9 grams (SD range: 8 - 11 grams)
______________________________
Lung interstitial cells:
Number of Lung interstitial cells is: 1e+11 cells (SD range: 1e+11 - 2e+11 cells)
Cell mass of Lung interstitial cells is: 740 pg (SD range: 670 - 820 pg)
Total cellular mass of Lung interstitial cells is: 101 grams (SD range: 86 - 118 grams)
Lifespan in rodents of Lung interstitial cells is: 44 days (SD range: 23 - 84 days)
Extrapolated cellular turnover rate of Lung interstitial cells is: 3e+09 cells per day (SD range: 2e+09 - 6e+09 cells per day)
Extrapolated cellular mass turnover rate of Lung interstitial cells is: 2.3 grams per day (SD range: 1.2 - 4.4 grams per day)
______________________________
Alveolar macrophages:
Number of Alveolar macrophages is: 3e+10 cells (SD range: 2e+10 - 4e+10 cells)
Lifespan of Alveolar macrophages is: 165 days (SD range: 97 - 280 days)
Cellular turnover rate of Alveolar macrophages is: 2e+08 cells per day (SD range: 1e+08 - 3e+08 cells per day)
Cell mass of Alveolar macrophages is: 2100 pg (SD range: 1900 - 2300 pg)
Cellular mass turnover rate of Alveolar macrophages is: 0.4 grams per day (SD range: 0.2 - 0.7 grams per day)
Total cellular mass of Alveolar macrophages is: 60 grams (SD range: 46 - 79 grams)
______________________________
Endothelial cells:
Number of Endothelial cells is: (6.0±2.0)×10¹¹ cells
Lifespan of Endothelial cells is: 2300±1200 days
Cellular turnover rate of Endothelial cells is: (2.0±2.0)×10⁸ cells per day
Cell mass of Endothelial cells is: 1200±500 pg
Cellular mass turnover rate of Endothelial cells is: 0.3±0.2 grams per day
Total cellular mass of Endothelial cells is: 700±300 grams
______________________________
Stomach epithelia:
Number of Stomach epithelia is: (1.7±0.4)×10¹⁰ cells
Lifespan of Stomach epithelia is: 13±9 days
Cellular turnover rate of Stomach epithelia is: (1.3±0.9)×10⁹ cells per day
Cell mass of Stomach epithelia is: 810±90 pg
Cellular mass turnover rate of Stomach epithelia is: 1.1±0.7 grams per day
Total cellular mass of Stomach epithelia is: 14±3 grams
______________________________
Small intestine epithelia:
Number of Small intestine epithelia is: (1.2±0.2)×10¹¹ cells
Lifespan of Small intestine epithelia is: 5±2 days
Cellular turnover rate of Small intestine epithelia is: (2.2±0.8)×10¹⁰ cells per day
Cell mass of Small intestine epithelia is: 840±160 pg
Cellular mass turnover rate of Small intestine epithelia is: 19±8 grams per day
Total cellular mass of Small intestine epithelia is: 100±20 grams
______________________________
Colon epithelia:
Number of Colon epithelia is: (6.0±2.0)×10¹⁰ cells
Lifespan of Colon epithelia is: 3.4±0.5 days
Cellular turnover rate of Colon epithelia is: (1.7±0.6)×10¹⁰ cells per day
Cell mass of Colon epithelia is: 840±160 pg
Cellular mass turnover rate of Colon epithelia is: 14±6 grams per day
Total cellular mass of Colon epithelia is: 50±20 grams
______________________________
Hepatocytes:
Number of Hepatocytes is: 2e+11 cells (SD range: 2e+11 - 3e+11 cells)
Cell mass of Hepatocytes is: 4300 pg (SD range: 3500 - 5300 pg)
Total cellular mass of Hepatocytes is: 980 grams (SD range: 710 - 1350 grams)
Lifespan in rodents of Hepatocytes is: 360 days (SD range: 310 - 420 days)
Extrapolated cellular turnover rate of Hepatocytes is: 6e+08 cells per day (SD range: 4e+08 - 1e+09 cells per day)
Extrapolated cellular mass turnover rate of Hepatocytes is: 3 grams per day (SD range: 2 - 4 grams per day)
______________________________
Glial cells:
Number of Glial cells is: (6.4±0.6)×10¹⁰ cells
Lifespan of Glial cells is: 21000±11000 days
Cellular turnover rate of Glial cells is: (3.1±1.6)×10⁶ cells per day
Cell mass of Glial cells is: 7000±2000 pg
Cellular mass turnover rate of Glial cells is: 0.021±0.012 grams per day
Total cellular mass of Glial cells is: 440±120 grams
______________________________
Neurons:
Number of Neurons is: (7.7±1.1)×10¹⁰ cells
Lifespan of Neurons is: (3.0±2.0)×10⁵ days
Cellular turnover rate of Neurons is: (3.0±2.0)×10⁵ cells per day
Cell mass of Neurons is: 7000±2000 pg
Cellular mass turnover rate of Neurons is: 0.0019±0.0013 grams per day
Total cellular mass of Neurons is: 530±150 grams
______________________________
Adipocytes:
Number of Adipocytes is: (3.4±0.5)×10¹⁰ cells
Lifespan of Adipocytes is: 4000±3000 days
Cellular turnover rate of Adipocytes is: (8.0±5.0)×10⁶ cells per day
Cell mass of Adipocytes is: (3.9±0.7)×10⁵ pg
Cellular mass turnover rate of Adipocytes is: 3±2 grams per day
Total cellular mass of Adipocytes is: 13300±1400 grams
______________________________
Myocytes:
Number of Myocytes is: (2.0±3.0)×10⁸ cells
Lifespan of Myocytes is: 18000±7000 days
Cellular turnover rate of Myocytes is: 13000±16000 cells per day
Cell mass of Myocytes is: (8.0±9.0)×10⁷ pg
Cellular mass turnover rate of Myocytes is: 0.9±0.4 grams per day
Total cellular mass of Myocytes is: 19000±2000 grams
______________________________
Cardiomyocytes:
Number of Cardiomyocytes is: (3.2±0.1)×10⁹ cells
Lifespan of Cardiomyocytes is: 56000±11000 days
Cellular turnover rate of Cardiomyocytes is: 57000±12000 cells per day
Cell mass of Cardiomyocytes is: 35000±3000 pg
Cellular mass turnover rate of Cardiomyocytes is: 0.0020±0.0005 grams per day
Total cellular mass of Cardiomyocytes is: 111±12 grams

/var/folders/75/2z9jf7bx0sqf07ypmf4yqgyhwmbx65/T/ipykernel_39940/1362151784.py:19: RuntimeWarning: invalid value encountered in log10
  log_vals = np.log10(values.astype(float))
/var/folders/75/2z9jf7bx0sqf07ypmf4yqgyhwmbx65/T/ipykernel_39940/1362151784.py:21: RuntimeWarning: invalid value encountered in remainder
  another_dig = 1*(log_vals %1 < 0.23)

,number,number lower bound,number upper bound,lifespan,lifespan lower bound,lifespan upper bound,cellular turnover rate,cellular turnover rate lower bound,cellular turnover rate upper bound,cell mass,...,total cellular mass upper bound,lifespan in rodents,lifespan in rodents lower bound,lifespan in rodents upper bound,extrapolated cellular turnover rate,extrapolated cellular turnover rate lower bound,extrapolated cellular turnover rate upper bound,extrapolated cellular mass turnover rate,extrapolated cellular mass turnover rate lower bound,extrapolated cellular mass turnover rate upper bound
cell type,,,,,,,,,,,,,,,,,,,,,
Erythrocytes,"25,500,000,000,000.000","25,000,000,000,000.000","26,000,000,000,000.000",119.000,116.000,122.000,"214,000,000,000.000","210,000,000,000.000","220,000,000,000.000",94.000,...,"2,500.000",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Neutrophils,"640,000,000,000.000","580,000,000,000.000","700,000,000,000.000",6.600,6.100,7.100,"60,000,000,000.000","45,000,000,000.000","75,000,000,000.000",300.000,...,220.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Monocytes,"5,200,000,000.000","3,500,000,000.000","7,600,000,000.000",3.500,3.000,4.100,"1,520,000,000.000","1,000,000,000.000","2,300,000,000.000",460.000,...,3.600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Thymocytes,"2,300,000,000.000","460,000,000.000","11,500,000,000.000",NaN,NaN,NaN,NaN,NaN,NaN,190.000,...,2.100,3.800,1.650,8.700,"610,000,000.000","100,000,000.000","3,700,000,000.000",0.113,0.019,0.690
Mature T cells,"710,000,000,000.000","320,000,000,000.000","1,560,000,000,000.000",320.000,240.000,430.000,"2,200,000,000.000","960,000,000.000","5,100,000,000.000",190.000,...,290.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
B cells progenitors,"5,500,000,000.000","3,800,000,000.000","7,900,000,000.000",NaN,NaN,NaN,NaN,NaN,NaN,190.000,...,1.490,0.830,0.410,1.660,"6,600,000,000.000","3,700,000,000.000","11,900,000,000.000",1.230,0.680,2.200
Transitional B cells,"2,800,000,000.000","1,170,000,000.000","6,700,000,000.000",NaN,NaN,NaN,NaN,NaN,NaN,190.000,...,1.270,9.900,8.500,11.600,"290,000,000.000","121,000,000.000","700,000,000.000",0.053,0.022,0.127
Mature B cells,"320,000,000,000.000","145,000,000,000.000","700,000,000,000.000",63.000,52.000,76.000,"5,100,000,000.000","2,200,000,000.000","11,700,000,000.000",190.000,...,130.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Dermal fibroblasts,"38,000,000,000.000","22,000,000,000.000","54,000,000,000.000",NaN,NaN,NaN,NaN,NaN,NaN,"2,300.000",...,130.000,140.000,120.000,160.000,"270,000,000.000","150,000,000.000","390,000,000.000",0.600,0.300,0.900
Epidermal cells,"120,000,000,000.000","90,000,000,000.000","150,000,000,000.000",31.000,27.000,35.000,"3,700,000,000.000","2,800,000,000.000","4,600,000,000.000",830.000,...,120.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Alveolar epithelial cells,"109,000,000,000.000","93,000,000,000.000","128,000,000,000.000",NaN,NaN,NaN,NaN,NaN,NaN,"2,200.000",...,300.000,32.000,29.000,36.000,"3,500,000,000.000","2,900,000,000.000","4,200,000,000.000",7.500,5.900,9.600
Bronchial epithelial cells,"10,400,000,000.000","9,400,000,000.000","11,500,000,000.000",139.000,109.000,180.000,"75,000,000.000","57,000,000.000","98,000,000.000",890.000,...,11.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Lung interstitial cells,"136,000,000,000.000","121,000,000,000.000","152,000,000,000.000",NaN,NaN,NaN,NaN,NaN,NaN,740.000,...,118.000,44.000,23.000,84.000,"3,100,000,000.000","1,630,000,000.000","5,900,000,000.000",2.300,1.210,4.400
Alveolar macrophages,"29,000,000,000.000","22,000,000,000.000","37,000,000,000.000",165.000,97.000,280.000,"180,000,000.000","100,000,000.000","320,000,000.000","2,100.000",...,79.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Endothelial cells,"600,000,000,000.000","400,000,000,000.000","800,000,000,000.000","2,300.000","1,100.000","3,500.000","240,000,000.000","70,000,000.000","410,000,000.000","1,200.000",...,"1,000.000",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Stomach epithelia,"17,000,000,000.000","13,000,000,000.000","21,000,000,000.000",13.000,4.000,22.000,"1,300,000,000.000","400,000,000.000","2,200,000,000.000",810.000,...,17.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Small intestine epithelia,"120,000,000,000.000","100,000,000,000.000","140,000,000,000.000",5.300,3.600,7.000,"22,000,000,000.000","14,000,000,000.000","30,000,000,000.000",840.000,...,120.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Colon epithelia,"60,000,000,000.000","40,000,000,000.000","80,000,000,000.000",3.400,2.900,3.900,"17,000,000,000.000","11,000,000,000.000","23,000,000,000.000",840.000,...,70.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Hepatocytes,"230,000,000,000.000","156,000,000,000.000","340,000,000,000.000",NaN,NaN,NaN,NaN,NaN,NaN,"4,300.000",...,"1,350.000",360.000,310.000,420.000,"640,000,000.000","430,000,000.000","960,000,000.000",2.700,1.900,3.800
Glial cells,"64,000,000,000.000","58,000,000,000.000","70,000,000,000.000","21,000.000","10,000.000","32,000.000","3,100,000.000","1,500,000.000","4,700,000.000","7,000.000",...,560.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Neurons,"77,000,000,000.000","66,000,000,000.000","88,000,000,000.000","300,000.000","100,000.000","500,000.000","300,000.000","100,000.000","500,000.000","7,000.000",...,680.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Adipocytes,"34,000,000,000.000","29,000,000,000.000","39,000,000,000.000","4,000.000","1,000.000","7,000.000","8,000,000.000","3,000,000.000","13,000,000.000","390,000.000",...,"14,700.000",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Myocytes,"200,000,000.000","-100,000,000.000","500,000,000.000","18,000.000","11,000.000","25,000.000","13,000.000","-3,000.000","29,000.000","80,000,000.000",...,"21,000.000",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Cardiomyocytes,"3,200,000,000.000","3,100,000,000.000","3,300,000,000.000","56,000.000","45,000.000","67,000.000","57,000.000","45,000.000","69,000.000","35,000.000",...,123.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
pd.read_csv("/Users/jayashankara2/Downloads/GTEx_Analysis_v8_Annotations_SampleAttributesDS.txt",sep="\t")

,SAMPID,SMATSSCR,SMCENTER,SMPTHNTS,SMRIN,SMTS,SMTSD,SMUBRID,SMTSISCH,SMTSPAX,...,SME1ANTI,SMSPLTRD,SMBSMMRT,SME1SNSE,SME1PCTS,SMRRNART,SME1MPRT,SMNUM5CD,SMDPMPRT,SME2PCTS
0,GTEX-1117F-0003-SM-58Q7G,NaN,B1,NaN,NaN,Blood,Whole Blood,0013756,"1,188.000",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,GTEX-1117F-0003-SM-5DWSB,NaN,B1,NaN,NaN,Blood,Whole Blood,0013756,"1,188.000",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,GTEX-1117F-0003-SM-6WBT7,NaN,B1,NaN,NaN,Blood,Whole Blood,0013756,"1,188.000",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,GTEX-1117F-0011-R10a-SM-AHZ7F,NaN,"B1, A1",NaN,NaN,Brain,Brain - Frontal Cortex (BA9),0009834,"1,193.000",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,GTEX-1117F-0011-R10b-SM-CYKQ8,NaN,"B1, A1",NaN,7.200,Brain,Brain - Frontal Cortex (BA9),0009834,"1,193.000",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22946,K-562-SM-E9EZC,NaN,NaN,NaN,NaN,Bone Marrow,Cells - Leukemia cell line (CML),EFO_0002067,NaN,NaN,...,"26,289,400.000","27,814,300.000",0.002,"26,121,600.000",49.840,0.006,0.995,NaN,0.000,50.262
22947,K-562-SM-E9EZI,NaN,NaN,NaN,NaN,Bone Marrow,Cells - Leukemia cell line (CML),EFO_0002067,NaN,NaN,...,"26,653,800.000","28,341,700.000",0.002,"26,553,400.000",49.906,0.007,0.995,NaN,0.000,50.205
22948,K-562-SM-E9EZO,NaN,NaN,NaN,NaN,Bone Marrow,Cells - Leukemia cell line (CML),EFO_0002067,NaN,NaN,...,"14,317,500.000","15,168,000.000",0.002,"14,163,500.000",49.730,0.007,0.995,NaN,0.000,50.241
22949,K-562-SM-E9EZT,NaN,NaN,NaN,NaN,Bone Marrow,Cells - Leukemia cell line (CML),EFO_0002067,NaN,NaN,...,"25,459,900.000","26,906,500.000",0.002,"25,259,100.000",49.802,0.007,0.995,NaN,0.000,50.253
22950,K-562-SM-E9EZZ,NaN,NaN,NaN,NaN,Bone Marrow,Cells - Leukemia cell line (CML),EFO_0002067,NaN,NaN,...,"22,341,200.000","23,740,600.000",0.002,"22,232,600.000",49.878,0.007,0.994,NaN,0.000,50.293